apiVersion: v1
kind: Pod
metadata:
  name: nettools
spec:
  serviceAccountName: nettools-sa
  containers:
    - name: nettools
      image: registry.access.redhat.com/ubi9/ubi-minimal
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
      # Restrict available commands to only tcpdump and netstat
      volumeMounts:
        - name: restrict-bin
          mountPath: /usr/local/bin
  volumes:
    - name: restrict-bin
      emptyDir: {}
  restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nettools-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nettools-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nettools-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nettools-role
subjects:
  - kind: ServiceAccount
    name: nettools-sa
