apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: tcpdump-debug-scc
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:<app-namespace>:node-debug-sa
